const x = 10;

try {
  x = 2;
} catch (err) {
  console.log(`Erro: ${err}`);
}
// "try catch": Uma forma de evidenciar algo que deu errado em um bloco de c√≥digo e exibir a mensagem de erro.
